"""Generate a human-readable RR evidence summary (Markdown).

This is written into journals/ so it can be committed as a small evidence
bundle without committing full run data.

Fail-closed
- This tool does NOT assert RR PASS by itself; it only summarizes the provided
  RR evidence artifacts.
- The rr_mvp.ps1/rr_mvp.sh script is responsible for pass/fail control flow.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Optional, Tuple


def _load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _get_code_sha(sig: Dict[str, Any]) -> Optional[str]:
    # New signature schema: sig["code"]["github_sha"]
    code = sig.get("code") or {}
    if isinstance(code, dict):
        sha = code.get("github_sha") or code.get("sha") or code.get("git_sha")
        if sha:
            return str(sha)
    # Old schema: no explicit code sha
    return None


def _schema(sig: Dict[str, Any]) -> str:
    if "signature_digest" in sig and "hashes_digest" in sig:
        return "v2"
    if "baseline_models" in sig and "manifest_sha256" in sig:
        return "v1"
    return "unknown"


def _extract_pr_auc_warnings_v1(sig: Dict[str, Any], threshold: float) -> Optional[str]:
    models = sig.get("baseline_models") or {}
    low: list[str] = []
    for mname, m in (models or {}).items():
        splits = (m or {}).get("splits") or {}
        for split, sm in (splits or {}).items():
            pr = (sm or {}).get("pr_auc")
            if pr is not None and float(pr) < threshold:
                low.append(f"{mname}/{split} (pr_auc={float(pr):.4f})")
    if not low:
        return None
    return "Low PR-AUC warning (MVP: warning-only): " + ", ".join(low)


def _extract_pr_auc_warnings_v2(sig: Dict[str, Any], threshold: float) -> Optional[str]:
    # v2: sig["baselines"][label][model]["splits"][split]["pr_auc"]
    baselines = sig.get("baselines") or {}
    low: list[str] = []
    for label, b in (baselines or {}).items():
        for mname, m in (b or {}).items():
            splits = (m or {}).get("splits") or {}
            for split, sm in (splits or {}).items():
                pr = (sm or {}).get("pr_auc")
                if pr is not None and float(pr) < threshold:
                    low.append(f"{label}:{mname}/{split} (pr_auc={float(pr):.4f})")
    if not low:
        return None
    return "Low PR-AUC warning (MVP: warning-only): " + ", ".join(low)


def _compare(sig_a: Dict[str, Any], sig_b: Dict[str, Any]) -> Tuple[bool, str]:
    """Best-effort comparison summary.

    rr_mvp scripts already do the hard fail-closed check; this is for humans.
    """
    sa = _schema(sig_a)
    sb = _schema(sig_b)
    if sa == "v2" and sb == "v2":
        da = sig_a.get("signature_digest")
        db = sig_b.get("signature_digest")
        ok = (da is not None) and (da == db)
        return ok, f"signature_digest A={da} B={db}"
    # v1 fallback: compare full JSON-ish core fields
    # (run_id differs; manifest hash differs; we can't claim determinism from v1)
    return False, "v1 signatures are not directly comparable (run_id/manifest differ). Use v2 rr_signature."


def build_md(base_run_id: str, run_a: str, run_b: str, sig_a: Path, sig_b: Path, threshold: float) -> str:
    sa = _load_json(sig_a)
    sb = _load_json(sig_b)

    schema_a = _schema(sa)
    schema_b = _schema(sb)

    compare_ok, compare_msg = _compare(sa, sb)

    # Shared fields
    config_hash = sa.get("config_hash") or sa.get("config_path") or "unknown"
    timezone = sa.get("timezone") or "unknown"
    seed = sa.get("seed") or "unknown"
    code_sha = _get_code_sha(sa) or "null (zip/no .git?)"

    lines: list[str] = []
    lines.append(f"# RR Evidence — RR-0001 — {base_run_id}")
    lines.append("")
    lines.append("This note is auto-generated by `tools/rr_evidence_md.py`.")
    lines.append("")
    lines.append("## Runs")
    lines.append(f"- A: `{run_a}`")
    lines.append(f"- B: `{run_b}`")
    lines.append("")
    lines.append("## Signature schema")
    lines.append(f"- A: `{schema_a}`")
    lines.append(f"- B: `{schema_b}`")
    lines.append("")
    lines.append("## Determinism summary (informational)")
    lines.append(f"- Compare: `{compare_msg}`")
    lines.append(f"- Determinism comparable here: `{compare_ok}`")
    lines.append("")
    lines.append("## Run identity")
    lines.append(f"- config_hash / config_path: `{config_hash}`")
    lines.append(f"- timezone: `{timezone}`")
    lines.append(f"- seed: `{seed}`")
    lines.append(f"- code_sha: `{code_sha}`")
    lines.append("")

    # Warnings
    warn = None
    if schema_a == "v2":
        warn = _extract_pr_auc_warnings_v2(sa, threshold)
    elif schema_a == "v1":
        warn = _extract_pr_auc_warnings_v1(sa, threshold)

    if warn:
        lines.append("## Warnings")
        lines.append(f"- {warn}")
        lines.append("")

    # Helpful digests
    if schema_a == "v2":
        lines.append("## Digests (v2)")
        lines.append(f"- signature_digest: `{sa.get('signature_digest')}`")
        lines.append(f"- hashes_digest: `{sa.get('hashes_digest')}`")
        lines.append(f"- features_digest: `{sa.get('features_digest')}`")
        lines.append(f"- baselines_digest: `{sa.get('baselines_digest')}`")
        lines.append("")

    lines.append("## Evidence files")
    lines.append(f"- sig_a: `{sig_a.as_posix()}`")
    lines.append(f"- sig_b: `{sig_b.as_posix()}`")
    lines.append("")
    lines.append("## Notes (fail-closed)")
    lines.append("- RR PASS/FAIL must be determined by the RR script exit code + logs.")
    lines.append("- If running from an unpacked zip without `.git`, `code_sha` may be null; config_hash + digests still support defensibility.")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base-run-id", required=True)
    ap.add_argument("--run-a", required=True)
    ap.add_argument("--run-b", required=True)
    ap.add_argument("--sig-a", required=True)
    ap.add_argument("--sig-b", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--warn-pr-auc-below", type=float, default=0.55)
    args = ap.parse_args()

    out = Path(args.out)
    md = build_md(
        base_run_id=args.base_run_id,
        run_a=args.run_a,
        run_b=args.run_b,
        sig_a=Path(args.sig_a),
        sig_b=Path(args.sig_b),
        threshold=float(args.warn_pr_auc_below),
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md, encoding="utf-8")


if __name__ == "__main__":
    main()
